name: viddit
description: A modern, optimized Reddit client built specifically for scrolling vertical videos and GIFs.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  webview_flutter: ^4.4.2
  shared_preferences: ^2.2.2
  video_player: ^2.8.1
  cached_network_image: ^3.3.0
  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  permission_handler: ^11.1.0
  google_fonts: ^6.1.0
  intl: ^0.18.1
  dio: ^5.9.2
  media_kit: ^1.2.6
  media_kit_video: ^2.0.1
  media_kit_libs_video: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
